title: Liam O' Brien
logo: "images/cropped-headshot.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a recent Computer Science graduate (1:1) looking for full time employment as a Software Developer/Engineer or related fields.
  <br><br>
  <a href="https://www.linkedin.com/in/liam-o-brien-668432158/"> <i class="fa fa-linkedin"> My LinkedIn </i> </a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
